my %targets = (
    "mingw-arm64" => {
        inherit_from     => [ "mingw-common" ],
        sys_id           => "MINGW64",
        bn_ops           => add("SIXTY_FOUR_BIT"),
        uplink_arch      => undef,
        shared_extension => ".dll",
    },
);
