#!/bin/bash

set -euo pipefail

script=$(realpath -- "${BASH_SOURCE[0]}")
conf_dir=$(dirname -- "${script}")
path=$(dirname -- "${conf_dir}")
source "${conf_dir}/service.sh"
require_root "${script}" "$@"

sysusers_file=/etc/sysusers.d/rotx.conf
unit_file=/etc/systemd/system/rotx.service

for command in systemctl systemd-sysusers getent runuser install chown chmod mktemp; do
	command -v "${command}" >/dev/null || fail "Required command is not installed: ${command}"
done

for file in rotx.service rotx.conf setup.sh uninstall.sh service.sh; do
	require_file "${conf_dir}/${file}"
done

require_file "${path}/rotx"
require_file "${path}/rotx.conf"
require_file /usr/bin/env

if [[ "${path}" == *[[:cntrl:]]* ]]; then
	fail "The deployment path must not contain control characters."
fi

for directory in "${path}/data" "${path}/data/tmp"; do
	if [ -L "${directory}" ] || { [ -e "${directory}" ] && [ ! -d "${directory}" ]; }; then
		fail "Refusing unsafe data directory: ${directory}"
	fi
done

if [ -e "${sysusers_file}" ] || [ -L "${sysusers_file}" ]; then
	require_file "${sysusers_file}"
	IFS= read -r header < "${sysusers_file}"
	[ "${header}" = '# Generated by mksvc for rotx' ] || fail "Conflicting system-user policy: ${sysusers_file}"
elif getent passwd rotx >/dev/null || getent group rotx >/dev/null; then
	check_identity
	passwd_entry=$(getent passwd rotx)
	IFS=: read -r username password user_id group_id description home shell <<< "${passwd_entry}"
	if [ "${home}" != "${path}" ] && [ "${home}" != /nonexistent ]; then
		fail "Refusing to reuse an unrelated account named rotx."
	fi
fi

if getent passwd rotx >/dev/null; then
	check_identity
fi

if [ -e "${unit_file}" ] || [ -L "${unit_file}" ]; then
	require_file "${unit_file}"
	[ -f "${sysusers_file}" ] || fail "An unrelated rotx.service is already installed."
fi

printf 'Installing rotx from %s\n' "${path}"
load_state=$(systemctl show --property=LoadState --value rotx.service)
if [ "${load_state}" != not-found ]; then
	systemctl stop rotx.service
fi

install -D -o root -g root -m 0644 "${conf_dir}/rotx.conf" "${sysusers_file}"
systemd-sysusers "${sysusers_file}"
check_identity

# Only deployment control files and private state change ownership, never site trees.
chown root:root "${path}" "${conf_dir}" "${path}/rotx"
chmod 0755 "${path}" "${conf_dir}" "${path}/rotx"
chown root:rotx "${path}/rotx.conf"
chmod 0640 "${path}/rotx.conf"

for file in rotx.service rotx.conf setup.sh uninstall.sh service.sh; do
	chown root:root "${conf_dir}/${file}"
	chmod 0644 "${conf_dir}/${file}"
done

install -d -o rotx -g rotx -m 0700 "${path}/data" "${path}/data/tmp"
chown -R -P --no-dereference rotx:rotx "${path}/data"

runuser -u rotx -- test -x "${path}" || fail "The rotx user cannot traverse the deployment's parent directories: ${path}"
runuser -u rotx -- test -r "${path}/rotx.conf" || fail "The rotx user cannot read rotx.conf."
runuser -u rotx -- test -x "${path}/rotx" || fail "The rotx user cannot execute the binary."

install -d -o root -g root -m 0755 /etc/systemd/system
temporary_unit=$(mktemp /etc/systemd/system/.rotx.XXXXXXXX)
trap 'rm -f -- "${temporary_unit}"' EXIT
render_service "${path}" "${conf_dir}/rotx.service" > "${temporary_unit}"
chmod 0644 "${temporary_unit}"
chown root:root "${temporary_unit}"
mv -f -- "${temporary_unit}" "${unit_file}"

systemctl daemon-reload
systemctl enable rotx.service
systemctl restart rotx.service
printf 'Installed and started rotx. Logs: journalctl -u rotx.service -f\n'
